### ISSUE TITLE
项目跑起来 访问不到服务

### ISSUE THREAD

**Issue by heppytt** [chenchensheng/spring-boot-cloud#1]
https://github.com/zhangxd1989/spring-boot-cloud/issues/24#issuecomment-501608304

**Comment by heppytt** [comment]
@陈辰生 你好。我把你版本更新后的代码在docker里面跑起来了。但是不知道如何去访问呢？麻烦你可不可以在告诉我一下。



项目的 README 里有讲呀

访问http://localhost:8761/ 访问不到服务。


那 8040 能访问吗, 你可以到我项目里提个 issue

你好8040也不行和上面一样。 我在你那个里面看不见 issuse

哎呀抱歉之前没开, 现在有了, 你可以先试下接口看看是不是正常的

curl -X POST -vu client:secret http://localhost:8060/uaa/oauth/token -H "Accept: application/json" -d "password=password&username=anil&grant_type=password&scope=read%20write"

**Comment by heppytt** [comment]
我试了一下 返回为空。
![image](https://user-images.githubusercontent.com/17058423/59417971-c4867f80-8dfa-11e9-9895-3b80ba513398.png)

**Comment by heppytt** [comment]
![image](https://user-images.githubusercontent.com/17058423/59417990-cfd9ab00-8dfa-11e9-80a2-3ec02970efc6.png)

**Comment by chanson-chan** [comment]
> 我试了一下 返回为空。
> ![image](https://user-images.githubusercontent.com/17058423/59417971-c4867f80-8dfa-11e9-9895-3b80ba513398.png)

你这个命令最后的分号换成双引号哈

**Comment by chanson-chan** [comment]
你可以加我 QQ 联系, 330266801

**Comment by heppytt** [comment]
> > 我试了一下 返回为空。
> > ![image](https://user-images.githubusercontent.com/17058423/59417971-c4867f80-8dfa-11e9-9895-3b80ba513398.png)
> 
> 你这个命令最后的分号换成双引号哈

![image](https://user-images.githubusercontent.com/17058423/59421684-99535e80-8e01-11e9-8105-3a008174fdc4.png)
有数据了

**Comment by heppytt** [comment]
> 你可以加我 QQ 联系, 330266801

加了你。通过一下。

**Comment by chanson-chan** [comment]
经排查是 docker-fo-mac 中给 docker 分配的资源太少引起的问题
